language: ruby

sudo: false

services:
  - docker

addons:
  apt:
    packages:
      - gdb
      - apport

env:
  global:
    - CC_TEST_REPORTER_ID=9f7f740ac1b6e264e1189fa07a6687a87bcdb9f3c0f4199d4344ab3b538e187e
    - KAFKA_HEAP_OPTS="-Xmx512m -Xms512m"

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7.1
  - jruby-9.2.9.0
  - jruby-9.2.10.0
  - jruby-9.2.11.1

before_install:
  # See https://github.com/travis-ci/travis-ci/issues/8920
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - ulimit -c
  - ulimit -a -S
  - ulimit -a -H
  - cat /proc/sys/kernel/core_pattern
  - cat /etc/default/apport
  - service --status-all || true
  - initctl list || true
  - gem update --system
  - |
    r_eng="$(ruby -e 'STDOUT.write RUBY_ENGINE')";
    if [ "$r_eng" == "jruby" ]; then
      sudo apt-get update && \
      sudo apt-get install -y git && \
      sudo apt-get install -y libpthread-stubs0-dev && \
      sudo apt-get install -y build-essential && \
      sudo apt-get install -y zlib1g-dev && \
      sudo apt-get install -y libssl-dev && \
      sudo apt-get install -y libsasl2-dev
    fi

before_script:
  - docker-compose up -d
  - cd ext && bundle exec rake && cd ..
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - ulimit -c unlimited -S
  - RUBYOPT=--debug bundle exec rspec --format documentation || RESULT=$?
  - if [[ ${RESULT} != 139 ]]; then echo "Skippping special segfault processing because result was ${RESULT}" && exit $RESULT; fi;
  - for i in $(find ./ -maxdepth 1 -name 'core*' -print); do bundle exec gdb -q ruby core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done;
  - exit 139

after_script:
  - docker-compose stop
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
